//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : 211506338
//  @ File Name : StaticData.h
//  @ Date : 2017/9/30
//  @ Author : ”‡µ§æ£
//
//


#if !defined(_STATICDATA_H)
#define _STATICDATA_H


class StaticData {
public:
	StaticData* shareeStaticData();
	void purqe();
	int intValueForKey(std::string key);
	char stringValueFromKey(std::string key);
	float floatValueFromKey(std::string key);
	bool booieanFromKey(std::string key);
	cocos2d::CCPoint pointFromKey(std::string key);
	cocos2d::CCRect rectFromKe(std::string key);
	void sizeFromKey(std::string key, cocos2d::CCSize );
protected:
	cocos::CCDictionary* _dictionary;
	std::string _staticFileName;
	bool int();
private:
	~StaticData();
	StaticData();
};

#endif  //_STATICDATA_H
