//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : 211506338
//  @ File Name : StaticData.cpp
//  @ Date : 2017/9/30
//  @ Author : ”‡µ§æ£
//
//


#include "StaticData.h"

StaticData* StaticData::shareeStaticData() {

}

void StaticData::purqe() {

}

int StaticData::intValueForKey(std::string key) {

}

char StaticData::stringValueFromKey(std::string key) {

}

float StaticData::floatValueFromKey(std::string key) {

}

bool StaticData::booieanFromKey(std::string key) {

}

cocos2d::CCPoint StaticData::pointFromKey(std::string key) {

}

cocos2d::CCRect StaticData::rectFromKe(std::string key) {

}

void StaticData::sizeFromKey(std::string key, cocos2d::CCSize ) {

}

bool StaticData::int() {

}

StaticData::~StaticData() {

}

StaticData::StaticData() {

}

